### ISSUE TITLE
Change Theme Color & Logo

### ISSUE THREAD

**Issue by rdhafiz** [rdhafiz/digency#16]
`#3E8FDA`

[Digency  -logo_pack.zip](https://github.com/rdhafiz/digency/files/12607402/Digency.-logo_pack.zip)

**Comment by asadullahchowdhury** [comment]
Logo and theme color has been changed

![image](https://github.com/rdhafiz/digency/assets/108151532/f5dcafb3-3417-4ded-a07c-5a1caca774d6)
